### ISSUE TITLE
Exercises for Masking

### ISSUE THREAD

**Issue by V-FOR-VEND3TTA** [V-FOR-VEND3TTA/web-in-motion#11]
Masking effects can add depth and creativity to interfaces, allowing elements to reveal or hide parts of content dynamically. Here are several exercises that progressively explore the possibilities of masking, from basic to more complex applications.

---

### 1. **Basic Text Masking with Background Image**

   - **Description**: Create a text masking effect that reveals a background image within the text, giving it a visually engaging look.
   - **Code Implementation**:
     - Use CSS `background-clip` to create the text masking effect:
       ```css
       .text-mask {
           font-size: 50px;
           font-weight: bold;
           color: transparent;
           background: url('your-image.jpg') no-repeat center;
           background-size: cover;
           -webkit-background-clip: text;
           background-clip: text;
       }
       ```
   - **Visual Outcome**: The text appears filled with the background image, creating a masked overlay within the text.
   - **Challenge**: Try animating the background position or image opacity for a subtle movement effect within the text.

---

### 2. **Circular Mask Hover Effect**

   - **Description**: Create a circular hover effect that reveals an image under an element. This effect is ideal for interactive elements like profile pictures or product previews.
   - **Code Implementation**:
     - Use CSS `clip-path` to apply a circular mask:
       ```css
       .masked-image {
           width: 200px;
           height: 200px;
           background: url('your-image.jpg') no-repeat center/cover;
           clip-path: circle(0% at 50% 50%);
           transition: clip-path 0.4s ease;
       }

       .masked-image:hover {
           clip-path: circle(50% at 50% 50%);
       }
       ```
   - **Visual Outcome**: A circular mask grows to reveal the image underneath, creating an interesting visual effect on hover.
   - **Challenge**: Experiment with different shapes (like ellipse or polygon) and hover speeds to customize the interaction.

---

### 3. **Text Reveal Mask Animation**

   - **Description**: Animate a mask that slides across the text to reveal it on page load or scroll. This effect is useful for headings or section titles.
   - **Code Implementation**:
     - Use CSS keyframes to animate a sliding mask over the text:
       ```css
       .text-reveal {
           font-size: 40px;
           position: relative;
           color: #fff;
       }

       .text-reveal::before {
           content: '';
           position: absolute;
           left: 0;
           top: 0;
           width: 100%;
           height: 100%;
           background: #3498db;
           transform-origin: left;
           transform: scaleX(0);
           transition: transform 0.5s ease-out;
       }

       .text-reveal.visible::before {
           transform: scaleX(1);
       }
       ```
       - Add JavaScript to toggle the visibility:
       ```javascript
       document.addEventListener('DOMContentLoaded', () => {
           document.querySelector('.text-reveal').classList.add('visible');
       });
       ```
   - **Visual Outcome**: A colored mask slides across the text, creating a clean and impactful reveal animation.
   - **Challenge**: Change the direction of the mask (e.g., top-to-bottom) or add a delay to achieve a staggered effect across multiple lines of text.

---

### 4. **Image Reveal Mask on Scroll**

   - **Description**: Reveal a hidden image as the user scrolls down the page, using masking to create an interactive experience.
   - **Code Implementation**:
     - Apply `clip-path` to create a scroll-triggered reveal:
       ```css
       .scroll-reveal {
           width: 100%;
           height: 300px;
           background: url('your-image.jpg') no-repeat center/cover;
           clip-path: inset(100% 0 0 0);
           transition: clip-path 1s ease;
       }

       .scroll-reveal.visible {
           clip-path: inset(0);
       }
       ```
       - Use JavaScript to detect scroll and apply the visible class:
       ```javascript
       window.addEventListener('scroll', () => {
           const element = document.querySelector('.scroll-reveal');
           const rect = element.getBoundingClientRect();
           if (rect.top < window.innerHeight) {
               element.classList.add('visible');
           }
       });
       ```
   - **Visual Outcome**: The image gradually reveals itself from top to bottom as the user scrolls.
   - **Challenge**: Change the reveal direction or try staggered scroll-based animations for multiple elements on the page.

---

### 5. **Gradient Mask Reveal on Button Hover**

   - **Description**: Add a gradient mask to a button, revealing a text shadow or icon when the user hovers. This creates a smooth, subtle effect for buttons.
   - **Code Implementation**:
     - Use CSS `mask-image` with a gradient to create the reveal effect:
       ```css
       .button-mask {
           padding: 10px 20px;
           font-size: 18px;
           color: #fff;
           background: #3498db;
           mask-image: linear-gradient(to right, transparent 50%, black 50%);
           transition: mask-position 0.4s ease;
           mask-size: 200% 100%;
           mask-position: 100% 0;
       }

       .button-mask:hover {
           mask-position: 0 0;
       }
       ```
   - **Visual Outcome**: On hover, the gradient mask slides, revealing the text or icon beneath.
   - **Challenge**: Try using a radial gradient mask or adding animation to make the effect more dynamic.

---

### 6. **Text Reveal through Image Mask**

   - **Description**: Mask text with an image, revealing the text as the image moves across it. This is a creative effect for hero sections or call-to-action banners.
   - **Code Implementation**:
     - Use CSS `mask-image` on the text:
       ```css
       .text-image-mask {
           font-size: 60px;
           font-weight: bold;
           background: #3498db;
           color: #fff;
           mask-image: url('your-image.jpg');
           mask-size: cover;
           mask-position: 0 0;
           transition: mask-position 1s ease;
       }

       .text-image-mask:hover {
           mask-position: 100% 0;
       }
       ```
   - **Visual Outcome**: The image slides over the text, gradually revealing it in a visually appealing way.
   - **Challenge**: Experiment with image position and scale, or add a timed delay for a more controlled reveal effect.

---

### 7. **Masked Video Background**

   - **Description**: Mask a video background within a shape (e.g., circle or polygon), creating an eye-catching animation for headers or content blocks.
   - **Code Implementation**:
     - Use CSS `clip-path` to apply the mask on the video element:
       ```css
       .video-mask {
           width: 300px;
           height: 300px;
           clip-path: circle(50%);
           overflow: hidden;
       }

       .video-mask video {
           width: 100%;
           height: 100%;
           object-fit: cover;
       }
       ```
   - **Visual Outcome**: A video plays within the masked shape, capturing attention in a unique way.
   - **Challenge**: Try different `clip-path` shapes or add a hover effect to change the mask shape.

---

### 8. **Multi-Layer Text Mask with Scroll Effect**

   - **Description**: Create a multi-layered text effect where each layer reveals with scrolling. This effect works well for landing pages or animated text headers.
   - **Code Implementation**:
     - Use CSS and JavaScript to apply staggered visibility to multiple text layers:
       ```css
       .layered-text span {
           display: block;
           font-size: 3rem;
           opacity: 0;
           transform: translateY(100%);
           transition: transform 0.6s, opacity 0.6s;
       }

       .layered-text.visible span:nth-child(1) { transition-delay: 0.2s; }
       .layered-text.visible span:nth-child(2) { transition-delay: 0.4s; }
       .layered-text.visible span:nth-child(3) { transition-delay: 0.6s; }
       ```
       - JavaScript to add visibility on scroll:
       ```javascript
       window.addEventListener('scroll', () => {
           const text = document.querySelector('.layered-text');
           const rect = text.getBoundingClientRect();
           if (rect.top < window.innerHeight) {
               text.classList.add('visible');
           }
       });
       ```
   - **Visual Outcome**: Each text layer slides in with a masked effect as the user scrolls, creating a layered reveal.
   - **Challenge**: Adjust the delays and apply different easing for each layer to vary the effect.

---

### 9. **Masked Background with Animated Text Reveal**

   - **Description**: Animate a background mask over text while revealing the text in sync. Great for interactive landing pages.
   - **Code Implementation**:
     - CSS for a moving mask effect:
       ```css
       .masked-bg-text {
           font-size: 3rem;
           color: transparent;
           background: linear-gradient(90deg, #3498db, #2ecc71);
           -webkit-background-clip: text;
           background-clip: text;
           animation: mask-move 3s linear infinite;
       }

       @keyframes mask-move {
           0% { background-position: -200%; }
           100% { background-position: 200%; }
       }
       ```
   - **Visual Outcome**: The gradient mask moves smoothly across the text, creating a dynamic color-changing effect.
   - **Challenge**: Experiment with gradient colors, animation duration, and directions for different visual outcomes. You can also combine this with a scroll trigger to activate the effect only when the text enters the viewport.

---

### 10. **Layered Mask Animation with Text and Background**

   - **Description**: Create a layered mask effect where both text and a background reveal together with a smooth animation, ideal for interactive headings or call-to-action sections.
   - **Code Implementation**:
     - Set up multiple layers and animate their masks in sync:
       ```css
       .layered-mask-container {
           position: relative;
           overflow: hidden;
           width: 100%;
           height: 200px;
       }

       .layered-mask-background, .layered-mask-text {
           position: absolute;
           top: 0;
           left: 0;
           width: 100%;
           height: 100%;
           transition: clip-path 1s ease;
       }

       .layered-mask-background {
           background-image: url('background.jpg');
           clip-path: polygon(0 0, 0 0, 0 100%, 0 100%);
       }

       .layered-mask-text {
           font-size: 3rem;
           font-weight: bold;
           color: #fff;
           clip-path: polygon(0 0, 0 0, 0 100%, 0 100%);
           background: #000;
           display: flex;
           align-items: center;
           justify-content: center;
       }

       .layered-mask-container.revealed .layered-mask-background,
       .layered-mask-container.revealed .layered-mask-text {
           clip-path: polygon(0 0, 100% 0, 100% 100%, 0 100%);
       }
       ```
       - Use JavaScript to add the `revealed` class:
       ```javascript
       window.addEventListener('load', () => {
           document.querySelector('.layered-mask-container').classList.add('revealed');
       });
       ```
   - **Visual Outcome**: Both the background image and the text animate in a synchronized mask reveal, creating a cohesive and engaging effect.
   - **Challenge**: Try altering the clip path polygons to create custom reveal directions (e.g., diagonal or zigzag). You could also add delays or stagger the animations for a more layered appearance.

---

These exercises provide a hands-on approach to mastering masking effects, helping you develop advanced techniques for crafting visually compelling interfaces. With each exercise, experiment by adjusting timing, easing functions, and directions to expand your understanding and creativity with masking.
