### ISSUE TITLE
Exercises for Parallax

### ISSUE THREAD

**Issue by V-FOR-VEND3TTA** [V-FOR-VEND3TTA/web-in-motion#15]
Parallax effects are a powerful tool for creating engaging, dynamic experiences, giving a sense of depth and immersion in a website or app. Below are exercises designed to help you understand and master parallax techniques, from simple scrolling effects to more complex, multi-layered animations.

---

### 1. **Simple Parallax Scrolling (One Layer)**

   - **Description**: Create a parallax effect where a background image scrolls at a slower pace than the content, creating a subtle depth effect.
   - **Code Implementation**:
     ```css
     .parallax {
         background-image: url('path/to/your/image.jpg');
         height: 100vh;
         background-attachment: fixed;
         background-position: center;
         background-repeat: no-repeat;
         background-size: cover;
     }
     ```
   - **Visual Outcome**: The background image stays fixed while the content scrolls, creating a simple parallax effect.
   - **Challenge**: Experiment with different background images and change the `background-position` to achieve unique effects (e.g., `top` or `bottom`).

---

### 2. **Multiple Layer Parallax**

   - **Description**: Create a scene with multiple layers, where each layer scrolls at different speeds to enhance the parallax effect.
   - **Code Implementation**:
     ```html
     <div class="parallax-container">
         <div class="parallax-layer layer-1"></div>
         <div class="parallax-layer layer-2"></div>
         <div class="parallax-layer layer-3"></div>
     </div>
     ```
     ```css
     .parallax-container {
         position: relative;
         height: 100vh;
         overflow: hidden;
     }

     .parallax-layer {
         position: absolute;
         top: 0;
         left: 0;
         width: 100%;
         height: 100%;
         background-size: cover;
         background-position: center;
         transition: transform 0.1s;
     }

     .layer-1 {
         background-image: url('path/to/layer1.jpg');
         transform: translateZ(-2px) scale(3);
     }

     .layer-2 {
         background-image: url('path/to/layer2.jpg');
         transform: translateZ(-1px) scale(2);
     }

     .layer-3 {
         background-image: url('path/to/layer3.jpg');
     }
     ```
   - **Visual Outcome**: As the user scrolls, the layers move at different speeds, creating a multi-layered parallax effect.
   - **Challenge**: Add `@media` queries to adjust the parallax effect on different screen sizes, or try adding more layers with varying levels of depth.

---

### 3. **Parallax on Scroll (Using JavaScript)**

   - **Description**: Create a more interactive parallax effect where elements move in response to the scroll position.
   - **Code Implementation**:
     ```html
     <div class="parallax-element"></div>
     ```
     ```css
     .parallax-element {
         position: absolute;
         top: 50%;
         left: 50%;
         transform: translate(-50%, -50%);
         width: 100px;
         height: 100px;
         background-color: red;
     }
     ```
     ```javascript
     window.addEventListener('scroll', function() {
         const element = document.querySelector('.parallax-element');
         const offset = window.scrollY * 0.5;  // Adjust this factor for speed
         element.style.transform = `translate(-50%, -50%) translateY(${offset}px)`;
     });
     ```
   - **Visual Outcome**: The element moves vertically as you scroll, creating a dynamic parallax effect.
   - **Challenge**: Adjust the `offset` calculation to move the element in a more complex path (e.g., horizontal and vertical). Add more elements with varying movement speeds for complexity.

---

### 4. **Parallax with Scale**

   - **Description**: Implement a parallax effect where images not only move vertically but also change scale (zoom in or out) as the user scrolls.
   - **Code Implementation**:
     ```html
     <div class="parallax-container">
         <div class="parallax-content">Content</div>
     </div>
     ```
     ```css
     .parallax-container {
         height: 100vh;
         overflow: hidden;
         position: relative;
     }

     .parallax-content {
         position: absolute;
         top: 0;
         left: 0;
         width: 100%;
         height: 100%;
         background-image: url('path/to/your-image.jpg');
         background-size: cover;
         background-position: center;
         transition: transform 0.1s ease-out;
     }
     ```
     ```javascript
     window.addEventListener('scroll', function() {
         const content = document.querySelector('.parallax-content');
         const scroll = window.scrollY;
         const scale = 1 + scroll / 1000;  // Change scale rate here
         content.style.transform = `scale(${scale})`;
     });
     ```
   - **Visual Outcome**: As you scroll, the image zooms in or out, while maintaining the parallax effect, creating a more immersive experience.
   - **Challenge**: Experiment with scaling factors and combine with other transformations like `translate` or `rotate`.

---

### 5. **Parallax with Text and Background Combination**

   - **Description**: Create an effect where the background and text move at different speeds, making the text seem to “float” above the background.
   - **Code Implementation**:
     ```html
     <div class="parallax-text-container">
         <div class="parallax-background"></div>
         <div class="parallax-text">This is some parallax text</div>
     </div>
     ```
     ```css
     .parallax-text-container {
         position: relative;
         height: 100vh;
         overflow: hidden;
     }

     .parallax-background {
         position: absolute;
         top: 0;
         left: 0;
         width: 100%;
         height: 100%;
         background-image: url('path/to/background.jpg');
         background-size: cover;
         background-position: center;
         transform: translateY(0);
     }

     .parallax-text {
         position: relative;
         z-index: 1;
         font-size: 2em;
         text-align: center;
         color: white;
         transform: translateY(0);
         transition: transform 0.1s ease-out;
     }
     ```
     ```javascript
     window.addEventListener('scroll', function() {
         const background = document.querySelector('.parallax-background');
         const text = document.querySelector('.parallax-text');
         
         const backgroundOffset = window.scrollY * 0.5;
         const textOffset = window.scrollY * 0.25;
         
         background.style.transform = `translateY(${backgroundOffset}px)`;
         text.style.transform = `translateY(${textOffset}px)`;
     });
     ```
   - **Visual Outcome**: The background image scrolls slower than the text, creating a “floating” effect for the text against the background.
   - **Challenge**: Experiment with the parallax speed for the text and background independently, or add more elements to the scene.

---

### 6. **Parallax for Fullscreen Hero Section**

   - **Description**: Create a fullscreen hero section where the background moves at a different speed than the text, making it feel like the content is floating above the scene.
   - **Code Implementation**:
     ```html
     <section class="hero">
         <div class="hero-background"></div>
         <div class="hero-text">Welcome to My Website</div>
     </section>
     ```
     ```css
     .hero {
         position: relative;
         height: 100vh;
         overflow: hidden;
     }

     .hero-background {
         position: absolute;
         top: 0;
         left: 0;
         width: 100%;
         height: 100%;
         background-image: url('path/to/hero-background.jpg');
         background-size: cover;
         background-position: center;
         transform: translateY(0);
     }

     .hero-text {
         position: absolute;
         top: 50%;
         left: 50%;
         transform: translate(-50%, -50%);
         font-size: 3em;
         color: white;
         z-index: 1;
     }
     ```
     ```javascript
     window.addEventListener('scroll', function() {
         const background = document.querySelector('.hero-background');
         const offset = window.scrollY * 0.2;
         background.style.transform = `translateY(${offset}px)`;
     });
     ```
   - **Visual Outcome**: As you scroll down the page, the hero background moves at a slower pace than the text, making the text appear to float over the background.
   - **Challenge**: Add a fade effect to the text as it moves or introduce additional layers with different movement speeds for more complexity.

---

### 7. **Interactive Mouse Movement Parallax**

   - **Description**: Create a mouse-move triggered parallax effect, where the elements respond to the mouse position, making the scene feel interactive.
   - **Code Implementation**:
     ```html
     <div class="parallax-mouse"></div>
     ```
     ```css
     .parallax-mouse {
         position: absolute;
         width: 300px;
         height: 300px;
         background-image: url('path/to/image.jpg');
         background-size: cover;
                  background-position: center;
         transition: transform 0.1s ease-out;
     }
   ```
   ```javascript
        document.addEventListener('mousemove', function(event) {
         const element = document.querySelector('.parallax-mouse');
         const xOffset = (event.clientX / window.innerWidth) - 0.5;
         const yOffset = (event.clientY / window.innerHeight) - 0.5;

         element.style.transform = `translate(${xOffset * 100}px, ${yOffset * 100}px)`;
     });
   ```

- **Visual Outcome**: As the user moves the mouse across the screen, the image moves in the opposite direction, creating an interactive, real-time parallax effect.
- **Challenge**: Adjust the `xOffset` and `yOffset` values to make the effect more subtle or exaggerated. You could also introduce additional elements with different movement speeds to create a more layered effect.

---

### 8. **Multi-Object Parallax with Mouse Movements**

   - **Description**: Implement a parallax effect where multiple elements (text and images) react to mouse movements in different ways, giving a 3D effect.
   - **Code Implementation**:
     ```html
     <div class="parallax-container">
         <div class="parallax-text">Welcome!</div>
         <div class="parallax-image"></div>
     </div>
     ```
     ```css
     .parallax-container {
         position: relative;
         height: 100vh;
         display: flex;
         justify-content: center;
         align-items: center;
         overflow: hidden;
     }

     .parallax-text {
         position: absolute;
         font-size: 3em;
         color: white;
         z-index: 2;
         transform: translate(0, 0);
     }

     .parallax-image {
         position: absolute;
         top: 0;
         left: 0;
         width: 100%;
         height: 100%;
         background-image: url('path/to/your-image.jpg');
         background-size: cover;
         background-position: center;
         transform: translate(0, 0);
     }
     ```
     ```javascript
     document.addEventListener('mousemove', function(event) {
         const text = document.querySelector('.parallax-text');
         const image = document.querySelector('.parallax-image');

         const xOffsetText = (event.clientX / window.innerWidth) - 0.5;
         const yOffsetText = (event.clientY / window.innerHeight) - 0.5;

         const xOffsetImage = (event.clientX / window.innerWidth) - 0.5;
         const yOffsetImage = (event.clientY / window.innerHeight) - 0.5;

         text.style.transform = `translate(${xOffsetText * 50}px, ${yOffsetText * 50}px)`;
         image.style.transform = `translate(${xOffsetImage * 30}px, ${yOffsetImage * 30}px)`;
     });
     ```
- **Visual Outcome**: The text and image move in response to mouse movement, but at different speeds and directions, creating a layered 3D parallax effect. The image moves less than the text, making the text appear to float in front of the background.
- **Challenge**: Add more elements with varying speeds and directions to enhance the depth effect. You can also experiment with adding a scale effect to one of the elements as the mouse moves.

---

### 9. **Parallax on Scroll with Dynamic Opacity**

   - **Description**: Create a parallax effect where the content changes opacity as the user scrolls, simulating a depth effect where distant elements fade out and closer elements fade in.
   - **Code Implementation**:
     ```html
     <div class="parallax-opacity">
         <h1>Parallax with Opacity</h1>
     </div>
     ```
     ```css
     .parallax-opacity {
         position: relative;
         height: 100vh;
         background-image: url('path/to/your-image.jpg');
         background-size: cover;
         background-position: center;
         transition: opacity 0.1s ease-out;
         display: flex;
         justify-content: center;
         align-items: center;
         text-align: center;
         color: white;
     }
     ```
     ```javascript
     window.addEventListener('scroll', function() {
         const parallaxElement = document.querySelector('.parallax-opacity');
         const scrollOffset = window.scrollY / window.innerHeight;
         
         const opacity = Math.max(1 - scrollOffset, 0.1); // Adjust the fade out speed here
         parallaxElement.style.opacity = opacity;
     });
     ```
- **Visual Outcome**: As the user scrolls, the background fades out, giving the impression that elements are moving farther away. This effect creates a subtle but dynamic feel.
- **Challenge**: Experiment with the speed at which opacity fades by adjusting the `scrollOffset` calculation. You can also add more elements that fade in or out at different rates for complexity.

---

### 10. **Full-Page Parallax with Parallax Image and Text Layers**

   - **Description**: Create a full-page layout where the background image and text move independently in a parallax fashion, and the image responds to scroll events for a deeper effect.
   - **Code Implementation**:
     ```html
     <section class="parallax-page">
         <div class="parallax-image"></div>
         <div class="parallax-text">Layered Parallax Effect</div>
     </section>
     ```
     ```css
     .parallax-page {
         position: relative;
         height: 100vh;
         overflow: hidden;
         display: flex;
         justify-content: center;
         align-items: center;
     }

     .parallax-image {
         position: absolute;
         top: 0;
         left: 0;
         width: 100%;
         height: 100%;
         background-image: url('path/to/your-image.jpg');
         background-size: cover;
         background-position: center;
         transition: transform 0.1s ease-out;
     }

     .parallax-text {
         position: relative;
         z-index: 1;
         font-size: 3em;
         color: white;
         text-align: center;
     }
     ```
     ```javascript
     window.addEventListener('scroll', function() {
         const image = document.querySelector('.parallax-image');
         const text = document.querySelector('.parallax-text');
         
         const imageOffset = window.scrollY * 0.3;
         const textOffset = window.scrollY * 0.1;

         image.style.transform = `translateY(${imageOffset}px)`;
         text.style.transform = `translateY(${textOffset}px)`;
     });
     ```
- **Visual Outcome**: As the user scrolls, the background image and text move independently at different speeds, enhancing the sense of depth. The background moves more slowly than the text, creating a parallax effect.
- **Challenge**: Add additional elements like buttons or icons that move at different speeds. Experiment with adding scale or opacity transitions for more dynamic interaction.

---

### Conclusion:

Parallax effects add rich interactivity and a sense of depth to web designs. These exercises, ranging from simple to complex, will help you understand how to implement parallax using CSS and JavaScript, and how to manipulate various elements like images, text, and mouse movements. Experimenting with different layers, speeds, and interaction methods will help you master parallax and create immersive experiences.
