### ISSUE TITLE
Exercises for Zoom

### ISSUE THREAD

**Issue by V-FOR-VEND3TTA** [V-FOR-VEND3TTA/web-in-motion#17]
Here are a few exercises focusing on zoom effects, which are often used to add depth, focus attention, or create dynamic visual interactions. These exercises will range from simple zoom effects to more complex ones using CSS and JavaScript.

---

### 1. **Basic Zoom-In on Hover (CSS)**

   - **Description**: Create a simple zoom effect where an image enlarges when the user hovers over it. This is a common effect used on product images or galleries.
   - **Code Implementation**:
     ```html
     <div class="zoom-container">
         <img src="your-image.jpg" alt="Zoom Image">
     </div>
     ```
     ```css
     .zoom-container {
         overflow: hidden;
         display: inline-block;
     }

     .zoom-container img {
         transition: transform 0.3s ease;
         width: 100%;
         height: auto;
     }

     .zoom-container:hover img {
         transform: scale(1.2);
     }
     ```
   - **Visual Outcome**: When the user hovers over the image, it will zoom in, enlarging the image within the container.
   - **Challenge**: Experiment with different `scale()` values to change the zoom level. Try adding a smooth `box-shadow` on hover to enhance the effect.

---

### 2. **Zoom In and Out with Scroll (CSS + JavaScript)**

   - **Description**: Implement a zoom effect where the user can scroll to zoom in and out of an image, creating a dynamic interaction based on mouse scroll.
   - **Code Implementation**:
     ```html
     <div class="zoom-scroll">
         <img src="your-image.jpg" alt="Zoom Scroll Image">
     </div>
     ```
     ```css
     .zoom-scroll {
         width: 100%;
         height: 100vh;
         overflow: hidden;
         display: flex;
         justify-content: center;
         align-items: center;
     }

     .zoom-scroll img {
         transition: transform 0.2s ease;
         width: 100%;
         height: auto;
     }
     ```
     ```javascript
     let scale = 1;

     document.querySelector('.zoom-scroll').addEventListener('wheel', function(event) {
         if (event.deltaY > 0) {
             scale += 0.1; // Zoom out
         } else {
             scale -= 0.1; // Zoom in
         }
         scale = Math.max(1, Math.min(scale, 3)); // Limit zoom range between 1x and 3x
         event.target.querySelector('img').style.transform = `scale(${scale})`;
     });
     ```
   - **Visual Outcome**: The user can zoom in and out on the image by scrolling, with smooth transitions. The zoom level is controlled by the mouse wheel.
   - **Challenge**: Add a `transform-origin` property to zoom in from a specific point (e.g., center, top-left). Also, experiment with setting a maximum zoom level.

---

### 3. **Zoom on Mouse Position (CSS + JavaScript)**

   - **Description**: Create a zoom effect where the image zooms into the area where the user’s mouse is hovering over. This effect is useful for showing product details in an interactive manner.
   - **Code Implementation**:
     ```html
     <div class="zoom-mouse">
         <img src="your-image.jpg" alt="Zoom Mouse Image">
     </div>
     ```
     ```css
     .zoom-mouse {
         position: relative;
         overflow: hidden;
     }

     .zoom-mouse img {
         transition: transform 0.3s ease;
         width: 100%;
         height: auto;
     }

     .zoom-mouse:hover img {
         transform: scale(1.5);
     }
     ```
     ```javascript
     const zoomImage = document.querySelector('.zoom-mouse img');
     document.querySelector('.zoom-mouse').addEventListener('mousemove', function(event) {
         const { offsetX, offsetY, target } = event;
         const xPercent = (offsetX / target.offsetWidth) * 100;
         const yPercent = (offsetY / target.offsetHeight) * 100;

         zoomImage.style.transformOrigin = `${xPercent}% ${yPercent}%`;
     });
     ```
   - **Visual Outcome**: As the user moves their mouse over the image, the area around the cursor zooms in, giving them a detailed view of that specific part of the image.
   - **Challenge**: Try adding a smooth transition for `transform-origin` and adjust the zoom scale dynamically based on the mouse position for more flexibility.

---

### 4. **Zoom and Pan Effect (CSS + JavaScript)**

   - **Description**: Implement an interactive zoom and pan effect where the user can click and drag to pan the image, while also using the scroll wheel to zoom in and out.
   - **Code Implementation**:
     ```html
     <div class="zoom-pan">
         <img src="your-image.jpg" alt="Zoom Pan Image">
     </div>
     ```
     ```css
     .zoom-pan {
         position: relative;
         width: 100%;
         height: 100vh;
         overflow: hidden;
         cursor: grab;
     }

     .zoom-pan img {
         transition: transform 0.2s ease;
         width: 100%;
         height: auto;
         transform-origin: center center;
     }
     ```
     ```javascript
     let scale = 1;
     let isDragging = false;
     let startX, startY;

     const image = document.querySelector('.zoom-pan img');
     const container = document.querySelector('.zoom-pan');

     container.addEventListener('mousedown', function(event) {
         isDragging = true;
         startX = event.clientX - container.offsetLeft;
         startY = event.clientY - container.offsetTop;
         container.style.cursor = 'grabbing';
     });

     container.addEventListener('mousemove', function(event) {
         if (isDragging) {
             const offsetX = event.clientX - startX;
             const offsetY = event.clientY - startY;
             image.style.transform = `scale(${scale}) translate(${offsetX}px, ${offsetY}px)`;
         }
     });

     container.addEventListener('mouseup', function() {
         isDragging = false;
         container.style.cursor = 'grab';
     });

     container.addEventListener('wheel', function(event) {
         if (event.deltaY > 0) {
             scale -= 0.1;
         } else {
             scale += 0.1;
         }
         scale = Math.max(1, Math.min(scale, 3)); // Limit zoom range
         image.style.transform = `scale(${scale})`;
     });
     ```
   - **Visual Outcome**: The user can click and drag to pan the image and use the mouse wheel to zoom in and out. The image should dynamically respond to both interactions.
   - **Challenge**: Implement inertia for the panning effect (i.e., the image should continue moving for a brief moment after the user stops dragging). Experiment with different zoom limits.

---

### 5. **Zoom-In on Scroll (CSS + JavaScript + Transform)**

   - **Description**: Create a smooth zoom-in effect that triggers when the user scrolls. The zoom level can increase incrementally as the user scrolls down the page.
   - **Code Implementation**:
     ```html
     <div class="zoom-scroll">
         <img src="your-image.jpg" alt="Zoom Scroll Image">
     </div>
     ```
     ```css
     .zoom-scroll {
         width: 100%;
         height: 100vh;
         display: flex;
         justify-content: center;
         align-items: center;
         overflow: hidden;
     }

     .zoom-scroll img {
         transition: transform 0.3s ease;
         width: 100%;
         height: auto;
     }
     ```
     ```javascript
     window.addEventListener('scroll', function() {
         const image = document.querySelector('.zoom-scroll img');
         const scrollY = window.scrollY;
         const zoomScale = 1 + scrollY / 1000; // Adjust zoom speed here
         image.style.transform = `scale(${zoomScale})`;
     });
     ```
   - **Visual Outcome**: As the user scrolls down the page, the image gradually zooms in. The zoom effect is incremental based on the scroll position.
   - **Challenge**: Experiment with different scaling formulas, such as using `Math.min()` or `Math.max()` to limit the maximum zoom scale. Add additional transitions like fading or panning while zooming.

---

### 6. **Zoom with CSS Grid and Hover (CSS)**

   - **Description**: Combine a grid layout with zoom effects to create a grid of images that zoom in on hover.
   - **Code Implementation**:
     ```html
     <div class="zoom-grid">
         <div class="zoom-item"><img src="image1.jpg" alt="Image 1"></div>
         <div class="zoom-item"><img src="image2.jpg" alt="Image 2"></div>
         <div class="zoom-item"><img src="image3.jpg" alt="Image 3"></div>
     </div>
     ```
     ```css
     .zoom-grid {
         display: grid;
         grid-template-columns: repeat(3, 1fr);
         gap: 20px;
     }

     .zoom-item img {
         width: 100%;
         height: auto;
         transition: transform 0.3s ease;
     }

     .zoom-item:hover img {
         transform: scale(1.2);
     }
```

## Complex Ones
Here are additional exercises for zoom effects to help you further explore different types of zoom interactions and enhance user experience:

---

### 7. **Zoom with Fade (CSS + JavaScript)**

   - **Description**: Combine zoom and fade effects to create a smooth transition where an image zooms in while also fading in or out. This effect can be useful for product galleries or visual elements in web design.
   - **Code Implementation**:
     ```html
     <div class="zoom-fade">
         <img src="your-image.jpg" alt="Zoom Fade Image">
     </div>
     ```
     ```css
     .zoom-fade {
         width: 100%;
         height: 100vh;
         display: flex;
         justify-content: center;
         align-items: center;
         overflow: hidden;
         opacity: 0;
         transition: opacity 0.5s ease;
     }

     .zoom-fade img {
         width: 100%;
         height: auto;
         transition: transform 0.3s ease;
     }

     .zoom-fade.show {
         opacity: 1;
     }

     .zoom-fade:hover img {
         transform: scale(1.2);
     }
     ```
     ```javascript
     window.addEventListener('load', function() {
         document.querySelector('.zoom-fade').classList.add('show');
     });
     ```
   - **Visual Outcome**: Upon page load, the image fades in while simultaneously zooming in when hovered over, creating a smooth visual effect that combines both transitions.
   - **Challenge**: Modify the timing of both the fade and zoom effects to achieve different transition speeds. Try adding a slight delay before the zoom effect triggers when the image is hovered.

---

### 8. **Zoom and Slide (CSS + JavaScript)**

   - **Description**: Implement a zoom effect combined with a sliding transition, where the image zooms in and slides into place from the left or right.
   - **Code Implementation**:
     ```html
     <div class="zoom-slide">
         <img src="your-image.jpg" alt="Zoom Slide Image">
     </div>
     ```
     ```css
     .zoom-slide {
         width: 100%;
         height: 100vh;
         overflow: hidden;
         position: relative;
     }

     .zoom-slide img {
         position: absolute;
         top: 50%;
         left: 50%;
         transform: translate(-50%, -50%) scale(1);
         transition: transform 0.3s ease, left 0.3s ease;
     }

     .zoom-slide:hover img {
         transform: translate(-50%, -50%) scale(1.3);
         left: 20%; /* Adjust based on desired slide distance */
     }
     ```
   - **Visual Outcome**: The image zooms in and slides from the left when hovered over, providing a dynamic and engaging effect.
   - **Challenge**: Try different directions of the slide (e.g., top, right, bottom) and adjust the zoom scale to find the right combination for different content.

---

### 9. **Zoom-In with Focus Area (CSS + JavaScript)**

   - **Description**: Implement a zoom effect where a specific area of the image is zoomed in, based on where the user clicks or hovers, allowing them to focus on specific details within an image.
   - **Code Implementation**:
     ```html
     <div class="zoom-focus">
         <img src="your-image.jpg" alt="Zoom Focus Image">
     </div>
     ```
     ```css
     .zoom-focus {
         width: 100%;
         height: 100vh;
         overflow: hidden;
         position: relative;
     }

     .zoom-focus img {
         width: 100%;
         height: auto;
         transition: transform 0.3s ease;
         cursor: pointer;
     }
     ```
     ```javascript
     const image = document.querySelector('.zoom-focus img');
     image.addEventListener('mousemove', function(event) {
         const { offsetX, offsetY, target } = event;
         const xPercent = (offsetX / target.offsetWidth) * 100;
         const yPercent = (offsetY / target.offsetHeight) * 100;

         image.style.transformOrigin = `${xPercent}% ${yPercent}%`;
         image.style.transform = 'scale(1.5)';
     });

     image.addEventListener('mouseleave', function() {
         image.style.transform = 'scale(1)';
     });
     ```
   - **Visual Outcome**: When the user moves their mouse over the image, the area around the cursor zooms in dynamically, offering an interactive experience focused on specific details of the image.
   - **Challenge**: Experiment with different zoom levels and smoothness of transitions. You can also trigger the zoom effect on click rather than hover, allowing for a more controlled interaction.

---

### 10. **Zoom-In with Fullscreen Transition (CSS + JavaScript)**

   - **Description**: Create a zoom effect that expands an image to full-screen size when clicked, effectively making the image zoom in to occupy the entire screen.
   - **Code Implementation**:
     ```html
     <div class="zoom-fullscreen">
         <img src="your-image.jpg" alt="Zoom Fullscreen Image">
     </div>
     ```
     ```css
     .zoom-fullscreen img {
         width: 100%;
         height: auto;
         transition: transform 0.5s ease;
         cursor: pointer;
     }

     .zoom-fullscreen.open img {
         transform: scale(3);
         position: fixed;
         top: 0;
         left: 0;
         z-index: 1000;
         width: 100%;
         height: 100%;
     }
     ```
     ```javascript
     const zoomImage = document.querySelector('.zoom-fullscreen img');
     zoomImage.addEventListener('click', function() {
         zoomImage.parentElement.classList.toggle('open');
     });
     ```
   - **Visual Outcome**: When the image is clicked, it zooms in and expands to fill the entire viewport. Clicking again will return the image to its original size.
   - **Challenge**: Try adding a background overlay or animation to transition the image more smoothly to full-screen. Additionally, experiment with adding a close button that allows the user to exit the full-screen mode.

---

### 11. **Zoom and Rotate (CSS)**

   - **Description**: Add a zoom effect combined with a subtle rotation, making the zoom effect appear more dynamic and interactive.
   - **Code Implementation**:
     ```html
     <div class="zoom-rotate">
         <img src="your-image.jpg" alt="Zoom Rotate Image">
     </div>
     ```
     ```css
     .zoom-rotate img {
         transition: transform 0.3s ease;
         width: 100%;
         height: auto;
     }

     .zoom-rotate:hover img {
         transform: scale(1.2) rotate(15deg);
     }
     ```
   - **Visual Outcome**: Upon hovering over the image, it zooms in while also rotating slightly, providing a more dynamic and engaging visual effect.
   - **Challenge**: Experiment with the rotation degree (e.g., rotate 45 degrees) and combine multiple transforms to create unique and more complex animations.

---

These zoom exercises cover a range of common use cases and can be adapted to a variety of UI design contexts, from product images to interactive elements. Experiment with different combinations, transitions, and trigger events to deepen your understanding of how zoom effects can enhance user experience.
