### ISSUE TITLE
Exercise for Easing 

### ISSUE THREAD

**Issue by V-FOR-VEND3TTA** [V-FOR-VEND3TTA/web-in-motion#3]
The following are five practical coding exercises for mastering easing functions in animations, tailored to gradually build your understanding and skills in animation flow and user experience.

---

### 1. **Basic Ease-In and Ease-Out**

   - **Description**: This exercise demonstrates how ease-in and ease-out animations affect movement speed at the start and end of the animation.
   - **Code Implementation**:
     - Using CSS, create a basic animation that moves a square from left to right across the screen.
     - Apply `ease-in` for one animation and `ease-out` for the other:
       ```css
       .ease-in {
           animation: moveEaseIn 2s ease-in;
       }
       .ease-out {
           animation: moveEaseOut 2s ease-out;
       }

       @keyframes moveEaseIn {
           from { transform: translateX(0); }
           to { transform: translateX(300px); }
       }

       @keyframes moveEaseOut {
           from { transform: translateX(0); }
           to { transform: translateX(300px); }
       }
       ```
   - **Visual Outcome**: The ease-in animation starts slowly and then accelerates, while ease-out starts faster and slows down towards the end.
   - **Challenge**: Experiment by combining ease-in and ease-out in one animation (`ease-in-out`). Observe the pacing changes, especially when adjusting duration (e.g., try `1s` vs. `3s`).

---

### 2. **Ease-In-Out with Hover Effect**

   - **Description**: Learn how ease-in-out transitions can smooth out hover effects, making them feel more responsive.
   - **Code Implementation**:
     - Create a button element that expands slightly on hover. Use `ease-in-out` for the transition:
       ```css
       .button {
           width: 150px;
           height: 50px;
           background-color: #3498db;
           transition: transform 0.4s ease-in-out;
       }

       .button:hover {
           transform: scale(1.1);
       }
       ```
   - **Visual Outcome**: The button grows smoothly when hovered, giving a pleasant feedback without abrupt changes.
   - **Challenge**: Adjust the duration and try using `ease-in` and `ease-out` separately on the `transform` property to see how each affects the hover experience.

---

### 3. **Bounce Effect: Simulating Gravity**

   - **Description**: This exercise introduces the bounce easing function, mimicking a ball dropping and bouncing off the ground.
   - **Code Implementation**:
     - In JavaScript, animate a ball element to move vertically, using a bounce effect:
       ```html
       <div class="ball"></div>
       <script>
       const ball = document.querySelector('.ball');
       ball.style.transition = 'transform 0.8s cubic-bezier(.34,1.56,.64,1)'; // Bounce effect
       
       let isFalling = true;
       setInterval(() => {
           if (isFalling) {
               ball.style.transform = 'translateY(200px)';
           } else {
               ball.style.transform = 'translateY(0)';
           }
           isFalling = !isFalling;
       }, 800);
       </script>
       ```
   - **Visual Outcome**: The ball drops and bounces in a realistic, gravity-inspired motion.
   - **Challenge**: Change the cubic-bezier values to control bounce height and "bounciness." Try experimenting with different ease functions like `ease-out` to observe subtle differences in the motion.

---

### 4. **Elastic Easing for Spring-Like Animations**

   - **Description**: Learn elastic easing by creating an element that overshoots its final position before settling, simulating a spring-like effect.
   - **Code Implementation**:
     - Apply a `cubic-bezier` function for the elastic effect:
       ```css
       .spring-box {
           width: 100px;
           height: 100px;
           background-color: #e74c3c;
           transition: transform 0.5s cubic-bezier(0.175, 0.885, 0.32, 1.275); // Elastic ease-out
       }

       .spring-box:hover {
           transform: scale(1.2);
       }
       ```
   - **Visual Outcome**: The element expands slightly past its final scale before snapping back, creating a "spring" feel.
   - **Challenge**: Experiment with different cubic-bezier values to make the effect more or less elastic. Try applying `elastic` easing to other properties like rotation or movement to see how the effect changes.

---

### 5. **Sequential Easing with Multiple Elements**

   - **Description**: Practice combining different easing functions for multiple elements, creating an elegant sequence where each element animates slightly after the previous one.
   - **Code Implementation**:
     - Use a series of boxes with a staggered delay, each box having a unique easing effect:
       ```css
       .box {
           width: 50px;
           height: 50px;
           background-color: #2ecc71;
           margin: 10px;
           display: inline-block;
           animation: moveRight 1s forwards;
       }

       .box:nth-child(1) { animation-timing-function: ease-in; animation-delay: 0s; }
       .box:nth-child(2) { animation-timing-function: ease-out; animation-delay: 0.2s; }
       .box:nth-child(3) { animation-timing-function: ease-in-out; animation-delay: 0.4s; }
       .box:nth-child(4) { animation-timing-function: cubic-bezier(0.68, -0.55, 0.27, 1.55); animation-delay: 0.6s; }

       @keyframes moveRight {
           from { transform: translateX(0); }
           to { transform: translateX(200px); }
       }
       ```
   - **Visual Outcome**: Each box moves to the right with a slight delay, and each easing function provides a distinct motion style.
   - **Challenge**: Add more elements, test additional easing functions, or increase delays to create a more complex sequence. Notice how different delays and easing combinations can create a smooth "wave" effect.

---

### 6. **Parallax Scrolling with Ease-in-out**

   - **Description**: This exercise introduces easing in a parallax scroll effect, creating a layered depth illusion.
   - **Code Implementation**:
     - Create two background layers that move at different speeds:
       ```html
       <div class="background" id="far"></div>
       <div class="background" id="near"></div>

       <script>
       window.addEventListener('scroll', () => {
           const scrollValue = window.scrollY;
           document.getElementById('far').style.transform = `translateY(${scrollValue * 0.3}px)`;
           document.getElementById('near').style.transform = `translateY(${scrollValue * 0.6}px)`;
       });
       </script>
       ```
   - **Visual Outcome**: As the user scrolls, the layers shift at different rates, creating a smooth parallax effect that enhances depth.
   - **Challenge**: Add easing to the transform values (using `ease-in-out` or `cubic-bezier`) to make the layers respond more dynamically to scroll. Test different scroll speeds for each layer to customize the effect.

---

Each of these exercises builds on previous concepts, helping you understand not just easing functions individually, but also how they can be creatively combined for engaging, user-friendly animations.
