### ISSUE TITLE
Exercises for Transformation and Morphing

### ISSUE THREAD

**Issue by V-FOR-VEND3TTA** [V-FOR-VEND3TTA/web-in-motion#9]
Here are some hands-on exercises for practicing transformation and morphing animations. These exercises explore shape and size transformations, combining rotations, scaling, and more complex morphing effects, suitable for creating interactive and engaging user experiences.

---

### 1. **Basic Scale and Rotate on Hover**

   - **Description**: Create a simple hover effect that scales and rotates an element to add a bit of interaction on hover.
   - **Code Implementation**:
     - Use CSS to scale and rotate the element on hover:
       ```css
       .hover-transform {
           transition: transform 0.3s ease;
       }

       .hover-transform:hover {
           transform: scale(1.1) rotate(10deg);
       }
       ```
   - **Visual Outcome**: The element slightly enlarges and tilts when hovered, creating a dynamic look.
   - **Challenge**: Experiment with different rotation angles and scaling factors to see how they change the interaction feel.

---

### 2. **Flip Card Effect**

   - **Description**: Build a 3D flip card effect to display additional content on the card's back side, useful for cards or product details.
   - **Code Implementation**:
     - Set up front and back card faces, and rotate on hover:
       ```css
       .card {
           width: 200px;
           height: 300px;
           perspective: 1000px;
       }

       .inner-card {
           width: 100%;
           height: 100%;
           transition: transform 0.6s;
           transform-style: preserve-3d;
           position: relative;
       }

       .card:hover .inner-card {
           transform: rotateY(180deg);
       }

       .card-face {
           position: absolute;
           width: 100%;
           height: 100%;
           backface-visibility: hidden;
       }

       .card-back {
           transform: rotateY(180deg);
       }
       ```
   - **Visual Outcome**: The card flips 180° to show the back side on hover.
   - **Challenge**: Add different animations to the front and back faces, like fading in the back face as it flips.

---

### 3. **Shape Morphing with Clip-Path**

   - **Description**: Animate a shape change from a circle to a square using CSS `clip-path`, ideal for buttons or interactive graphics.
   - **Code Implementation**:
     - Use CSS `clip-path` and keyframes to morph the shape:
       ```css
       .morph-shape {
           width: 100px;
           height: 100px;
           background-color: #3498db;
           clip-path: circle(50%);
           transition: clip-path 0.6s ease-in-out;
       }

       .morph-shape:hover {
           clip-path: inset(0);
       }
       ```
   - **Visual Outcome**: The element smoothly transforms from a circle to a square when hovered.
   - **Challenge**: Try creating more complex shapes with clip-path values or combine with color changes.

---

### 4. **Elastic Bounce Transformation**

   - **Description**: Implement a “bounce” effect using scaling to simulate an elastic bounce when an element is clicked.
   - **Code Implementation**:
     - Use CSS keyframes to create the elastic bounce effect:
       ```css
       .bounce {
           display: inline-block;
           animation: bounce 1s ease-out forwards;
       }

       @keyframes bounce {
           0%, 100% { transform: scale(1); }
           30% { transform: scale(1.2); }
           50% { transform: scale(0.8); }
           70% { transform: scale(1.1); }
       }
       ```
       - Trigger the bounce effect on click:
       ```javascript
       document.querySelector('.bounce').addEventListener('click', function() {
           this.classList.remove('bounce'); // reset animation
           void this.offsetWidth; // trigger reflow
           this.classList.add('bounce'); // restart animation
       });
       ```
   - **Visual Outcome**: The element bounces when clicked, giving a playful interactive effect.
   - **Challenge**: Change the timing of the keyframes to create different bounce intensities or durations.

---

### 5. **SVG Path Morphing**

   - **Description**: Use an SVG graphic to morph between two shapes, such as from a star to a heart. This exercise introduces morphing with SVG paths for a smooth effect.
   - **Code Implementation**:
     - Use JavaScript and CSS to animate the path:
       ```html
       <svg width="100" height="100" viewBox="0 0 24 24">
           <path id="morph-path" d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2z" fill="#3498db"/>
       </svg>
       ```
       ```javascript
       const path = document.querySelector('#morph-path');
       path.addEventListener('mouseover', () => {
           path.setAttribute('d', 'M12 21.35l-1.45-1.32C5.4 15.36 2 12.28 2 8.5 2 5.42 4.42 3 7.5 3S13 5.42 13 8.5c0 1.54-.49 2.94-1.3 4.15L12 21.35z');
       });
       ```
   - **Visual Outcome**: The SVG shape morphs smoothly into another shape when hovered.
   - **Challenge**: Experiment with different SVG path shapes or use libraries like GreenSock’s MorphSVG for advanced morphing options.

---

### 6. **Accordion Morphing Panels**

   - **Description**: Create an accordion effect where each panel morphs in size when clicked, commonly used for FAQ sections.
   - **Code Implementation**:
     - Use JavaScript to toggle the height and apply CSS transitions:
       ```css
       .accordion-panel {
           height: 0;
           overflow: hidden;
           transition: height 0.5s ease;
       }

       .accordion-panel.active {
           height: auto;
       }
       ```
       ```javascript
       document.querySelectorAll('.accordion-header').forEach(header => {
           header.addEventListener('click', () => {
               const panel = header.nextElementSibling;
               panel.classList.toggle('active');
           });
       });
       ```
   - **Visual Outcome**: Each panel expands smoothly when clicked, enhancing readability.
   - **Challenge**: Add a rotate icon that morphs as the panel opens/closes to show the active state visually.

---

### 7. **Morphing Button Animation on Click**

   - **Description**: Implement a button that morphs from a square to a rounded shape when clicked, adding a smooth UI transition.
   - **Code Implementation**:
     - Use CSS and JavaScript to change the shape on click:
       ```css
       .morph-button {
           width: 100px;
           height: 40px;
           background-color: #3498db;
           border-radius: 4px;
           transition: width 0.3s ease, border-radius 0.3s ease;
       }

       .morph-button.active {
           width: 150px;
           border-radius: 20px;
       }
       ```
       ```javascript
       document.querySelector('.morph-button').addEventListener('click', function() {
           this.classList.toggle('active');
       });
       ```
   - **Visual Outcome**: The button expands and becomes rounded on click, providing a clear visual cue of interaction.
   - **Challenge**: Change the color and add a fade-out effect when the button morphs for a layered animation.

---

### 8. **Expanding Circle Loader**

   - **Description**: Create a loader animation where a small circle expands and then resets, perfect for a loading screen.
   - **Code Implementation**:
     - Use CSS keyframes to animate the circle expansion:
       ```css
       .loader {
           width: 20px;
           height: 20px;
           background-color: #3498db;
           border-radius: 50%;
           animation: expandAndReset 1.2s ease-in-out infinite;
       }

       @keyframes expandAndReset {
           0% { transform: scale(1); }
           50% { transform: scale(1.5); }
           100% { transform: scale(1); }
       }
       ```
   - **Visual Outcome**: The circle smoothly expands and contracts, signaling a loading process.
   - **Challenge**: Create multiple circles with staggered delays to form a ripple effect.

---

### 9. **Morphing Dropdown Menu**

   - **Description**: Design a dropdown menu where each item morphs in size when hovered, making it more engaging.
   - **Code Implementation**:
     - Use CSS to morph the item’s width on hover:
       ```css
       .dropdown-item {
           width: 150px;
           transition: width 0.3s ease, background-color 0.3s ease;
       }

       .dropdown-item:hover {
           width: 180px;
           background-color: #2ecc71;
       }
       ```
   - **Visual Outcome**: Each item slightly expands in width when hovered, creating a smooth interactive feel.
   - **Challenge**: Add an icon or text that appears or changes color as the item expands.

---

### 10. **Layered Mask Animation with Text and Background**

   - **Description**: Create a layered mask effect where both text and a background reveal together with a smooth animation, ideal for interactive headings or call-to-action sections.
   - **Code Implementation**:
     - Set up multiple layers and animate their masks in sync:
       ```css
       .layered-mask-container {
           position: relative;
           overflow: hidden;
           width: 100%;
           height: 200px;
       }

       .layered-mask-background, .layered-mask-text {
           position: absolute;
           top: 0;
           left: 0;
           width: 100%;
           height: 100%;
           transition: clip-path 1s ease;
       }

       .layered-mask-background {
           background-image: url('background.jpg');
           clip-path: polygon(0 0, 0 0, 0 100%, 0 100%);
       }

       .layered-mask-text {
           font-size: 3rem;
           font-weight: bold;
           color: #fff;
           clip-path: polygon(0 0, 0 0, 0 100%, 0 100%);
           background: #000;
           display: flex;
           align-items: center;
           justify-content: center;
       }

       .layered-mask-container.revealed .layered-mask-background,
       .layered-mask-container.revealed .layered-mask-text {
           clip-path: polygon(0 0, 100% 0, 100% 100%, 0 100%);
       }
       ```
       - Use JavaScript to add the `revealed` class:
       ```javascript
       window.addEventListener('load', () => {
           document.querySelector('.layered-mask-container').classList.add('revealed');
       });
       ```
   - **Visual Outcome**: Both the background image and the text animate in a synchronized mask reveal, creating a cohesive and engaging effect.
   - **Challenge**: Try altering the clip path polygons to create custom reveal directions (e.g., diagonal or zigzag). You could also add delays or stagger the animations for a more layered appearance.

---

These exercises provide a hands-on approach to mastering masking effects, helping you develop advanced techniques for crafting visually compelling interfaces. With each exercise, experiment by adjusting timing, easing functions, and directions to expand your understanding and creativity with masking.
